apiVersion: v1
kind: Service
metadata:
  name: pyapp
  labels:
    app: pyapp
spec:
  type: LoadBalancer
  selector:
    app: pyapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
